# ================= SERVER =================
server.port=8082
# ================= DATABASE =================
# Khi chạy Docker, hãy đổi localhost thành postgres nếu dùng network chung
spring.datasource.url=jdbc:postgresql://localhost:5432/chat_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# ================= MINIO =================
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin

# Khai báo cả 2 biến này để tránh lỗi ở các lớp khác nhau gọi sai tên
minio.bucket=chat-files
minio.bucket-name=chat-files

# # URL này để trả về cho React hiển thị ảnh
# minio.external-url=http://localhost:9000

# Bạn phải lấy Link Tunnel của Port 9000 trong tab Ports của VS Code
minio.external-url=https://tqgwvv8g-9001.asse.devtunnels.ms/
# 🔥 URL PUBLIC của Backend (Port 8082)
app.public-url=https://tqgwvv8g-8082.asse.devtunnels.ms/
# ================= MQTT =================
mqtt.broker=tcp://localhost:1883
mqtt.client-id=chatapp-backend
mqtt.username=
mqtt.password=